openapi: 3.0.3
info: 
  title: Shop Review API
  version: 1.0.0
  description: |
    # Features
    - Get reviews
    - Post review
  termsOfService: https://tastylog.com/terms/
  contact:
    name: Customer Support
    url: https://tastylog.com/contact/
    email: support-desk@tastylog.com
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT


paths: {}
