openapi: 3.0.0

info:
  title: Shop Review API
  version: 1.0.0

paths:
  /shops/{shopId}/reviews:
    post:
      summary: Create review
      parameters:
        - in: path
          name: shopId
          required: true
          schema:
            type: string
          example: absdefg
        - name: x-api-key
          in: header
          description: Request user's identifier
          schema:
            type: string
          example: xxxx-xxxx-xxxx-xxxx
        - name: token
          in: cookie
          description: One time token
          schema:
            type: string
          example: xxxx-xxxx-xxxx-xxxx
      tags: [shops]
      deprecated: false
      responses:
        '201':
          description: Success operation
