openapi: 3.0.0
info:
  title: Shop Review API
  version: 1.0.0
servers:
  - url: http://localhost:{port}
    description: Local development
    variables:
      port:
        enum:
          - "3000"
          - "8080"
        default: "3000"
  - url: http://it1.tastylog.com
    description: Integration Test
  - url: http://stg.tastylog.com
    description: Staging
  - url: http://api.tastylog.com
    description: Production
paths: {}
